import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Createtokenhomepage</Link>
        </li>
        <li>
          <Link to="/launchpad">Launchpad</Link>
        </li>
        <li>
          <Link to="/launchpadchoosewallet">Launchpadchoosewallet</Link>
        </li>
        <li>
          <Link to="/launchpadresult">Launchpadresult</Link>
        </li>
        <li>
          <Link to="/launchpadloading">Launchpadloading</Link>
        </li>
        <li>
          <Link to="/homepagecodexapp">Homepagecodexapp</Link>
        </li>
        <li>
          <Link to="/daohomegenerator">DAOHOMEGENERATOR</Link>
        </li>
        <li>
          <Link to="/daoselecttesnet">DAOselecttesnet</Link>
        </li>
        <li>
          <Link to="/createprojectright">CreateProjectRight</Link>
        </li>
        <li>
          <Link to="/createtokenpageselectblockchain">
            Createtokenpageselectblockchain
          </Link>
        </li>
        <li>
          <Link to="/createtokenliquidgeneratortoken">
            Createtokenliquidgeneratortoken
          </Link>
        </li>
        <li>
          <Link to="/createtokensuccescreatetoken">
            Createtokensuccescreatetoken
          </Link>
        </li>
        <li>
          <Link to="/mytokenreadcontractdefault">
            Mytokenreadcontractdefault
          </Link>
        </li>
        <li>
          <Link to="/tokenwritedefault">TokenWritedefault</Link>
        </li>
        <li>
          <Link to="/nocodenfthomepage">NOCODENFThomepage</Link>
        </li>
        <li>
          <Link to="/wallets">Wallets</Link>
        </li>
        <li>
          <Link to="/daodescribe">DAOdescribe</Link>
        </li>
        <li>
          <Link to="/mytokenreadcontractdetailall">
            Mytokenreadcontractdetailall
          </Link>
        </li>
        <li>
          <Link to="/mytokenwritecontractdetailall">
            Mytokenwritecontractdetailall
          </Link>
        </li>
        <li>
          <Link to="/homepagecodexappone">HomepagecodexappOne</Link>
        </li>
        <li>
          <Link to="/frame371316">Frame371316</Link>
        </li>
        <li>
          <Link to="/daodefinetokenholder">DAOdefinetokenholder</Link>
        </li>
        <li>
          <Link to="/daodefinemultisigmembers">DAOdefinemultisigmembers</Link>
        </li>
        <li>
          <Link to="/nocodenftgeneralinfo">NOCODENFTgeneralinfo</Link>
        </li>
        <li>
          <Link to="/nocodenftcontract">NOCODENFTCONTRACT</Link>
        </li>
        <li>
          <Link to="/daodefinea">DAOdefinea</Link>
        </li>
        <li>
          <Link to="/daodefineb">DAOdefineb</Link>
        </li>
        <li>
          <Link to="/nocodenftfeatures">NOCODENFTfeatures</Link>
        </li>
        <li>
          <Link to="/nocodenftmarket">NOCODENFTMARKET</Link>
        </li>
        <li>
          <Link to="/daoresulta">DAOresulta</Link>
        </li>
        <li>
          <Link to="/daoresultb">DAOresultb</Link>
        </li>
        <li>
          <Link to="/nocodenftdeploy">NOCODENFTDEPLOY</Link>
        </li>
        <li>
          <Link to="/daoapprovetransactiona">DAOapprovetransactiona</Link>
        </li>
        <li>
          <Link to="/nocodenftloading">NOCODENFTloading</Link>
        </li>
        <li>
          <Link to="/homepagecontributorupdatedregister">
            HomepagecontributorUpdatedregister
          </Link>
        </li>
        <li>
          <Link to="/regristrationpagecontributordev">
            Regristrationpagecontributordev
          </Link>
        </li>
        <li>
          <Link to="/accountsuccesscontributordeveloper">
            Accountsuccesscontributordeveloper
          </Link>
        </li>
        <li>
          <Link to="/accountsuccesscontributordeveloperone">
            AccountsuccesscontributordeveloperOne
          </Link>
        </li>
        <li>
          <Link to="/accountsuccesscontributorgeneraluser">
            Accountsuccesscontributorgeneraluser
          </Link>
        </li>
        <li>
          <Link to="/regristrationpagecontributorgeneraluser">
            Regristrationpagecontributorgeneraluser
          </Link>
        </li>
        <li>
          <Link to="/myaccounthome">Myaccounthome</Link>
        </li>
        <li>
          <Link to="/myaccountnotiftotalpoints">Myaccountnotiftotalpoints</Link>
        </li>
        <li>
          <Link to="/myaccounttotalprojectsone">MyaccounttotalprojectsOne</Link>
        </li>
        <li>
          <Link to="/myaccounttotalrewardone">MyaccounttotalrewardOne</Link>
        </li>
        <li>
          <Link to="/myaccountdeveloper">Myaccountdeveloper</Link>
        </li>
        <li>
          <Link to="/myaccountnotiftotalpointsone">
            MyaccountnotiftotalpointsOne
          </Link>
        </li>
        <li>
          <Link to="/myaccounttotalprojects">Myaccounttotalprojects</Link>
        </li>
        <li>
          <Link to="/myaccounttotalreward">Myaccounttotalreward</Link>
        </li>
        <li>
          <Link to="/myaccountdevcheckpoints">Myaccountdevcheckpoints</Link>
        </li>
        <li>
          <Link to="/myaccountdevcheckpointsviewmore">
            Myaccountdevcheckpointsviewmore
          </Link>
        </li>
        <li>
          <Link to="/myaccountcheckpointviewmore">
            Myaccountcheckpointviewmore
          </Link>
        </li>
        <li>
          <Link to="/myaccountcheckpointsviewmore">
            Myaccountcheckpointsviewmore
          </Link>
        </li>
        <li>
          <Link to="/myaccountcontributedprojectsviewmore">
            Myaccountcontributedprojectsviewmore
          </Link>
        </li>
        <li>
          <Link to="/myaccountcontributedprojectsall">
            Myaccountcontributedprojectsall
          </Link>
        </li>
        <li>
          <Link to="/myaccountcontributedprojectsviewmoreone">
            MyaccountcontributedprojectsviewmoreOne
          </Link>
        </li>
        <li>
          <Link to="/myaccountcontributeviewmore">
            Myaccountcontributeviewmore
          </Link>
        </li>
        <li>
          <Link to="/myaccountgeneraluserrewardtransaction">
            Myaccountgeneraluserrewardtransaction
          </Link>
        </li>
        <li>
          <Link to="/myaccountgeneraluserrewardtransactionall">
            Myaccountgeneraluserrewardtransactionall
          </Link>
        </li>
        <li>
          <Link to="/myaccountrewardtransactiondefault">
            Myaccountrewardtransactiondefault
          </Link>
        </li>
        <li>
          <Link to="/myaccountrewardtransactionall">
            Myaccountrewardtransactionall
          </Link>
        </li>
        <li>
          <Link to="/myaccountgeneraluserdeleteaccountsucces">
            Myaccountgeneraluserdeleteaccountsucces
          </Link>
        </li>
        <li>
          <Link to="/myaccountgeneraluserdeleteaccountconfirmation">
            Myaccountgeneraluserdeleteaccountconfirmation
          </Link>
        </li>
        <li>
          <Link to="/myaccountdeveloperdeleteaccountsucces">
            Myaccountdeveloperdeleteaccountsucces
          </Link>
        </li>
        <li>
          <Link to="/forumcodexalldetail">Forumcodexalldetail</Link>
        </li>
        <li>
          <Link to="/forumcodexaddnewtopic">Forumcodexaddnewtopic</Link>
        </li>
        <li>
          <Link to="/forumcodexeducation">Forumcodexeducation</Link>
        </li>
        <li>
          <Link to="/forumcodexeducationalldetail">
            Forumcodexeducationalldetail
          </Link>
        </li>
        <li>
          <Link to="/forumcodexsuggestion">Forumcodexsuggestion</Link>
        </li>
        <li>
          <Link to="/forumcodexeducationalldetailone">
            ForumcodexeducationalldetailOne
          </Link>
        </li>
        <li>
          <Link to="/forumcodexprojects">Forumcodexprojects</Link>
        </li>
        <li>
          <Link to="/forumcodexprojectsalldetail">
            Forumcodexprojectsalldetail
          </Link>
        </li>
        <li>
          <Link to="/forumcodexprojectsone">ForumcodexprojectsOne</Link>
        </li>
        <li>
          <Link to="/forumcodexprojectsalldetailone">
            ForumcodexprojectsalldetailOne
          </Link>
        </li>
        <li>
          <Link to="/forumcodexdevelopment">Forumcodexdevelopment</Link>
        </li>
        <li>
          <Link to="/forumcodexdevelopmentalldetail">
            Forumcodexdevelopmentalldetail
          </Link>
        </li>
        <li>
          <Link to="/forumcodexpullrequest">Forumcodexpullrequest</Link>
        </li>
        <li>
          <Link to="/forumcodexpullrequestalldetail">
            Forumcodexpullrequestalldetail
          </Link>
        </li>
        <li>
          <Link to="/forumcodexpullrequestmessage">
            Forumcodexpullrequestmessage
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
